spring:
  main:
    web-application-type: none

  datasource:
    url: jdbc:postgresql://localhost:5432/naneandreasyan
    username: naneandreasyan
    password: 1234

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

app:
  scraper:
    url: https://catalog.aua.am/course-descriptions-2024/