spring:
  main:
    web-application-type: servlet

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/naneandreasyan}
    username: ${SPRING_DATASOURCE_USERNAME:naneandreasyan}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

app:
  scraper:
    url: https://catalog.aua.am/course-descriptions-2024/

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}

genai:
  model: gemini-2.0-flash-001
  api:
    key: ${GENAI_API_KEY}