spring:
  main:
    web-application-type: servlet

  datasource:
    url: jdbc:postgresql://localhost:5432/naneandreasyan
    username: naneandreasyan
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

app:
  scraper:
    url: https://catalog.aua.am/course-descriptions-2024/